### PR TITLE
Revert "Dev/add UT for ceremony._key_is_duplicated (#88)"

### LINKED ISSUE #132: Bug: Incompatible payload from CLI
### What happened?

After ceremony is complete, the bootstrap process fails.

Impacts:

repository-service-tuf-cli >= [v0.0.1a4](https://github.com/vmware/repository-service-tuf-cli/releases/tag/v0.0.1a4)

```
Configuration correct for bins? [y/n]: y
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Error 422 [{'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc':         │
│ ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyid'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', │
│ 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', │
│ 'timestamp', 'keys', 'timestamp_1', 'key', 'keyid'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles',    │
│ 'bins', 'keys', 'bins_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyid'], 'msg':  │
│ 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}]                                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### What steps did you take?

- Deploy rstuf
- Use the latest CLI
- Perform the ceremony online OR generate a payload with the CLI offline and upload it

### What behavior did you expect?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rdimitrov**
The following PR reverts commit b2afa4688fb646dbbd56f8e98767cbc70ca7a092, because it introduces an incompatible payload with `rstuf-api`.

**Reproduce:**
* Deploy rstuf
* Use the latest CLI
* Perform the ceremony online OR generate a payload with the CLI offline and upload it

**Impacts:**
* repository-service-tuf-cli >= [v0.0.1a4](https://github.com/vmware/repository-service-tuf-cli/releases/tag/v0.0.1a4) 

**Reference:** 
```
Configuration correct for bins? [y/n]: y
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Error 422 [{'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc':         │
│ ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyid'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'snapshot', 'keys', 'snapshot_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', │
│ 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', │
│ 'timestamp', 'keys', 'timestamp_1', 'key', 'keyid'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'timestamp', 'keys', 'timestamp_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles',    │
│ 'bins', 'keys', 'bins_1', 'filename'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keytype'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'scheme'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyid'], 'msg':  │
│ 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyid_hash_algorithms'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'settings', 'roles', 'bins', 'keys', 'bins_1', 'key', 'keyval'], 'msg': 'field required', 'type': 'value_error.missing'}]                                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Closes #132 

(edited)

### CODE REVIEW

**Comment by rdimitrov** [comment]
FYI: @KAUTH

**Review by kairoaraujo — APPROVED** [review]

**Review by MVrachev — APPROVED** [review]
By reverting commit https://github.com/vmware/repository-service-tuf-cli/commit/b2afa4688fb646dbbd56f8e98767cbc70ca7a092 you are also removing the unit tests.
Do we need to reopen https://github.com/vmware/repository-service-tuf-cli/issues/16 again?

Also, maybe it's worth waiting for @KAUTH comment before merging as we are reverting his work.

**Comment by kairoaraujo** [comment]
> By reverting commit [b2afa46](https://github.com/vmware/repository-service-tuf-cli/commit/b2afa4688fb646dbbd56f8e98767cbc70ca7a092) you are also removing the unit tests. Do we need to reopen #16 again?
> 
> Also, maybe it's worth waiting for @KAUTH comment before merging as we are reverting his work.

We will need to reopen #16 
Also, I will need to add the ceremony in the Functional test 😄

**Comment by KAUTH** [comment]
> By reverting commit [b2afa46](https://github.com/vmware/repository-service-tuf-cli/commit/b2afa4688fb646dbbd56f8e98767cbc70ca7a092) you are also removing the unit tests. Do we need to reopen #16 again?
> 
> Also, maybe it's worth waiting for @KAUTH comment before merging as we are reverting his work.

Thanks @MVrachev, I'm taking it a look now. If we don't find a fix quickly and it's critical then we can indeed revert it and after finding a solution I can cherry pick the corrected commit from my local repo and re-push.

@kairoaraujo indeed another goodie for the Functional tests 😄

**Pull request merged**
